var searchModuleIndex = [
"README",
"rxv",
"main",
"main",
"main",
"main",
"main",
"main",
"main",
"main",
];

var searchIndex = [
"merge",
"concat",
"just",
"from_channel",
"from_slice",
"create",
"empty",
"throw",
"range",
"repeat",
"defer_",
"interval",
"timer",
"Item",
"of",
"from_error",
"rxv.Item[T]",
"is_error",
"get_value",
"send_context",
"CloseChannelStrategy",
"Iterable",
"Observable",
"ChannelIterable",
"new_channel_iterable",
"ChannelIterable[T]",
"observe",
"SliceIterable",
"new_slice_iterable",
"SliceIterable[T]",
"observe",
"CreateIterable",
"new_create_iterable",
"CreateIterable[T]",
"observe",
"ObservableImpl",
"ObservableImpl[T]",
"str",
"rxv.ObservableImpl[T]",
"observe",
"filter",
"take",
"for_each",
"distinct",
"distinct_until_changed",
"first",
"last",
"timeout",
"map_",
"scan_",
"reduce_",
"count_",
"ObservableImpl[f64]",
"average_f64",
"sum_f64",
"RxOption",
"Options",
"build_context",
"parse_options",
"rxv.Options",
"build_channel_t",
"get_pool",
"is_eager_observation",
"with_buffer_size",
"with_pool",
"with_context",
"with_eager_observation",
"with_error_strategy",
"flat_map_",
"concat_map_",
"ProducerFn",
"MapFn",
"PredicateFn",
"NextFn",
"ErrFn",
"CompletedFn",
"BackpressureStrategy",
"OnErrorStrategy",
"ObservationStrategy",
"CloseChannelStrategy.from",
"BackpressureStrategy.from",
"OnErrorStrategy.from",
"ObservationStrategy.from",
];

var searchModuleData = [
["<div align=\"center\">","index.html"],
["<div align=\"center\">","rxv.html"],
["","main.html"],
["","main.html"],
["","main.html"],
["","main.html"],
["","main.html"],
["","main.html"],
["","main.html"],
["","main.html"],
];

var searchData = [
["rxv","merge combines two observables by interleaving their emissions.","rxv.html#merge","fn "],
["rxv","concat concatenates multiple observables sequentially.","rxv.html#concat","fn "],
["rxv","just emits each provided value then completes.","rxv.html#just","fn "],
["rxv","from_channel wraps an existing channel as an ObservableImpl.","rxv.html#from_channel","fn "],
["rxv","","rxv.html#from_slice","fn "],
["rxv","create builds an ObservableImpl from a producer function.","rxv.html#create","fn "],
["rxv","empty completes immediately without emitting any item.","rxv.html#empty","fn "],
["rxv","throw emits a single error then completes.","rxv.html#throw","fn "],
["rxv","range emits integers in [start, start+count).","rxv.html#range","fn "],
["rxv","repeat emits the same value `count` times.","rxv.html#repeat","fn "],
["rxv","","rxv.html#defer_","fn "],
["rxv","interval emits sequential integers starting at 0 at each `period_ms` millisecond","rxv.html#interval","fn "],
["rxv","timer emits a single 0 after `delay_ms` milliseconds, then completes.","rxv.html#timer","fn "],
["rxv","","rxv.html#Item","struct "],
["rxv","","rxv.html#of","fn "],
["rxv","","rxv.html#from_error","fn "],
["rxv","","rxv.html#rxv.Item[T]","type "],
["rxv","","rxv.html#rxv.Item[T].is_error","fn (rxv.Item[T])"],
["rxv","","rxv.html#rxv.Item[T].get_value","fn (rxv.Item[T])"],
["rxv","","rxv.html#rxv.Item[T].send_context","fn (rxv.Item[T])"],
["rxv","","rxv.html#CloseChannelStrategy","enum "],
["rxv","Iterable[T] is the base interface for anything that can be observed.","rxv.html#Iterable","interface "],
["rxv","","rxv.html#Observable","interface "],
["rxv","---- ChannelIterable -------------------------------------------------------- Us","rxv.html#ChannelIterable","struct "],
["rxv","","rxv.html#new_channel_iterable","fn "],
["rxv","","rxv.html#ChannelIterable[T]","type "],
["rxv","","rxv.html#ChannelIterable[T].observe","fn (ChannelIterable[T])"],
["rxv","---- SliceIterable ----------------------------------------------------------","rxv.html#SliceIterable","struct "],
["rxv","","rxv.html#new_slice_iterable","fn "],
["rxv","","rxv.html#SliceIterable[T]","type "],
["rxv","","rxv.html#SliceIterable[T].observe","fn (SliceIterable[T])"],
["rxv","---- CreateIterable ---------------------------------------------------------","rxv.html#CreateIterable","struct "],
["rxv","","rxv.html#new_create_iterable","fn "],
["rxv","","rxv.html#CreateIterable[T]","type "],
["rxv","","rxv.html#CreateIterable[T].observe","fn (CreateIterable[T])"],
["rxv","","rxv.html#ObservableImpl","struct "],
["rxv","","rxv.html#ObservableImpl[T]","type "],
["rxv","","rxv.html#ObservableImpl[T].str","fn (ObservableImpl[T])"],
["rxv","","rxv.html#rxv.ObservableImpl[T]","type "],
["rxv","","rxv.html#rxv.ObservableImpl[T].observe","fn (rxv.ObservableImpl[T])"],
["rxv","","rxv.html#rxv.ObservableImpl[T].filter","fn (rxv.ObservableImpl[T])"],
["rxv","","rxv.html#rxv.ObservableImpl[T].take","fn (rxv.ObservableImpl[T])"],
["rxv","","rxv.html#rxv.ObservableImpl[T].for_each","fn (rxv.ObservableImpl[T])"],
["rxv","distinct suppresses duplicate items, emitting only items not previously seen.","rxv.html#rxv.ObservableImpl[T].distinct","fn (rxv.ObservableImpl[T])"],
["rxv","distinct_until_changed suppresses consecutive duplicate items.","rxv.html#rxv.ObservableImpl[T].distinct_until_changed","fn (rxv.ObservableImpl[T])"],
["rxv","first emits only the first item from the source.","rxv.html#rxv.ObservableImpl[T].first","fn (rxv.ObservableImpl[T])"],
["rxv","last emits only the last item from the source.","rxv.html#rxv.ObservableImpl[T].last","fn (rxv.ObservableImpl[T])"],
["rxv","timeout emits an error if no item is received within `timeout_ms` milliseconds.","rxv.html#rxv.ObservableImpl[T].timeout","fn (rxv.ObservableImpl[T])"],
["rxv","","rxv.html#map_","fn "],
["rxv","scan_ applies an accumulator over the stream, emitting each intermediate result.","rxv.html#scan_","fn "],
["rxv","reduce_ applies an accumulator over the entire stream, emitting only the final v","rxv.html#reduce_","fn "],
["rxv","count_ returns an Observable emitting the number of items emitted by the source.","rxv.html#count_","fn "],
["rxv","","rxv.html#ObservableImpl[f64]","type "],
["rxv","average_f64 computes the average of f64 values emitted by the source.","rxv.html#ObservableImpl[f64].average_f64","fn (ObservableImpl[f64])"],
["rxv","sum_f64 computes the sum of f64 values emitted by the source.","rxv.html#ObservableImpl[f64].sum_f64","fn (ObservableImpl[f64])"],
["rxv","RxOption is a functional option applied to an Options struct.","rxv.html#RxOption","type "],
["rxv","Options holds resolved operator configuration.","rxv.html#Options","struct "],
["rxv","build_context returns the context for an operator.","rxv.html#Options.build_context","fn (Options)"],
["rxv","parse_options merges a list of RxOption functions into an Options value.","rxv.html#parse_options","fn "],
["rxv","","rxv.html#rxv.Options","type "],
["rxv","build_channel_t creates a typed buffered channel.","rxv.html#rxv.Options.build_channel_t","fn (rxv.Options)"],
["rxv","get_pool returns the pool size if set.","rxv.html#rxv.Options.get_pool","fn (rxv.Options)"],
["rxv","","rxv.html#rxv.Options.is_eager_observation","fn (rxv.Options)"],
["rxv","--- built-in option constructors ---","rxv.html#with_buffer_size","fn "],
["rxv","","rxv.html#with_pool","fn "],
["rxv","","rxv.html#with_context","fn "],
["rxv","","rxv.html#with_eager_observation","fn "],
["rxv","","rxv.html#with_error_strategy","fn "],
["rxv","flat_map_ transforms each item by applying a function that returns an observable","rxv.html#flat_map_","fn "],
["rxv","concat_map_ transforms each item by applying a function that returns an observab","rxv.html#concat_map_","fn "],
["rxv","ProducerFn[T] sends items onto a channel given a context.","rxv.html#ProducerFn","type "],
["rxv","MapFn[T, U] transforms a T value into a U, or returns an error.","rxv.html#MapFn","type "],
["rxv","PredicateFn[T] tests a value; return true to keep it.","rxv.html#PredicateFn","type "],
["rxv","NextFn[T] is called for each next value in for_each.","rxv.html#NextFn","type "],
["rxv","ErrFn is called when an error item is received.","rxv.html#ErrFn","type "],
["rxv","CompletedFn is called when the stream completes.","rxv.html#CompletedFn","type "],
["rxv","BackpressureStrategy controls how full channels are handled.","rxv.html#BackpressureStrategy","enum "],
["rxv","OnErrorStrategy controls operator behaviour on errors.","rxv.html#OnErrorStrategy","enum "],
["rxv","ObservationStrategy controls eager vs lazy subscription.","rxv.html#ObservationStrategy","enum "],
["rxv","","rxv.html#CloseChannelStrategy.from","fn "],
["rxv","","rxv.html#BackpressureStrategy.from","fn "],
["rxv","","rxv.html#OnErrorStrategy.from","fn "],
["rxv","","rxv.html#ObservationStrategy.from","fn "],
];

